const NAVIGATION_ROUTES = Object.freeze({
    ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
    ACCOUNT_NAVIGATOR: 'ACCOUNT_NAVIGATOR',
    FEED_NAVIGATOR: 'FEED_NAVIGATOR',
    LISTING_DETAILS_SCREEN: 'LISTING_DETAILS_SCREEN',
    LISTING_EDIT_SCREEN: 'LISTING_EDIT_SCREEN',
    LISTINGS_SCREEN: 'LISTINGS_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    MESSAGES_SCREEN: 'MESSAGES_SCREEN',
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    WELCOME_SCREEN: 'WELCOME_SCREEN',
});

export default NAVIGATION_ROUTES;